# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  header-jeffl8n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: jeffl8n-header.svg

          # Options
          template: classic
          base: header, activity, community, repositories, metadata
          user: jeffl8n
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_lines: yes

  iso_calender-jeffl8n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: jeffl8n-iso_calender.svg

          # Options
          template: classic
          base: ""
          user: jeffl8n
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  achievements-jeffl8n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: jeffl8n-achievements.svg

          # Options
          template: classic
          base: achievements
          user: jeffl8n
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0

  languages-jeffl8n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: jeffl8n-languages.svg

          # Options
          template: classic
          base: ""
          user: jeffl8n
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage

  habits-jeffl8n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: jeffl8n-habits.svg

          # Options
          template: classic
          base: ""
          user: jeffl8n
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes

          
  header-jel3-sf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SF_METRICS_TOKEN }}

          filename: jel3-sf-header.svg

          # Options
          template: classic
          base: header, activity, community, repositories, metadata
          user: jel3-sf
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          repositories_affiliations: owner, collaborator
          plugin_lines: yes

  iso_calender-jel3-sf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SF_METRICS_TOKEN }}

          filename: jel3-sf-iso_calender.svg

          # Options
          template: classic
          base: ""
          user: jel3-sf
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  achievements-jel3-sf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SF_METRICS_TOKEN }}

          filename: jel3-sf-achievements.svg

          # Options
          template: classic
          base: achievements
          user: jel3-sf
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0

  languages-jel3-sf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SF_METRICS_TOKEN }}

          filename: jel3-sf-languages.svg

          # Options
          template: classic
          base: ""
          user: jel3-sf
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage

  habits-jel3-sf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SF_METRICS_TOKEN }}

          filename: jel3-sf-habits.svg

          # Options
          template: classic
          base: ""
          user: jel3-sf
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          repositories_affiliations: owner, collaborator
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes