# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics-jeffl8n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: jeffl8n-header.svg

          # Options
          template: classic
          base: header, activity, community, repositories, metadata
          user: jeffl8n
          config_timezone: ${{ secrets.USER_TIMEZONE }}

  iso_calender-jeffl8n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: jeffl8n-iso_calender.svg

          # Options
          template: classic
          base: ""
          user: jeffl8n
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  achievements-jeffl8n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: jeffl8n-achievements.svg

          # Options
          template: classic
          base: achievements
          user: jeffl8n
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0

  languages-jeffl8n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: jeffl8n-languages.svg

          # Options
          template: classic
          base: ""
          user: jeffl8n
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage


          
  github-metrics-jel3-sf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SF_METRICS_TOKEN }}

          filename: jel3-sf-header.svg

          # Options
          template: classic
          base: header, activity, community, repositories, metadata
          user: jel3-sf
          config_timezone: ${{ secrets.USER_TIMEZONE }}

  iso_calender-jel3-sf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SF_METRICS_TOKEN }}

          filename: jel3-sf-iso_calender.svg

          # Options
          template: classic
          base: ""
          user: jel3-sf
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  achievements-jel3-sf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SF_METRICS_TOKEN }}

          filename: jel3-sf-achievements.svg

          # Options
          template: classic
          base: achievements
          user: jel3-sf
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0

  languages-jel3-sf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SF_METRICS_TOKEN }}

          filename: jel3-sf-languages.svg

          # Options
          template: classic
          base: ""
          user: jel3-sf
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage