# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  header-jeffl8n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: jeffl8n-header.svg

          # Options
          template: classic
          base: header
          user: jeffl8n
          config_timezone: ${{ vars.USER_TIMEZONE }}
          repositories_skipped: |
            ${{ vars.REPOS_SKIPPED }}

  activity-jeffl8n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: jeffl8n-activity.svg

          # Options
          template: classic
          base: activity
          user: jeffl8n
          config_timezone: ${{ vars.USER_TIMEZONE }}
          repositories_skipped: |
            ${{ vars.REPOS_SKIPPED }}

  repositories-jeffl8n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: jeffl8n-repositories.svg

          # Options
          template: classic
          base: repositories
          user: jeffl8n
          config_timezone: ${{ vars.USER_TIMEZONE }}
          repositories_skipped: |
            ${{ vars.REPOS_SKIPPED }}

  iso_calender-jeffl8n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: jeffl8n-iso_calender.svg

          # Options
          template: classic
          base: ""
          user: jeffl8n
          config_timezone: ${{ vars.USER_TIMEZONE }}
          repositories_skipped: |
            ${{ vars.REPOS_SKIPPED }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  achievements-jeffl8n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: jeffl8n-achievements.svg

          # Options
          template: classic
          base: achievements
          user: jeffl8n
          config_timezone: ${{ vars.USER_TIMEZONE }}
          repositories_skipped: |
            ${{ vars.REPOS_SKIPPED }}
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0

  languages-jeffl8n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: jeffl8n-languages.svg

          # Options
          template: classic
          base: ""
          user: jeffl8n
          config_timezone: ${{ vars.USER_TIMEZONE }}
          repositories_skipped: |
            ${{ vars.REPOS_SKIPPED }}
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage

  habits-jeffl8n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: jeffl8n-habits.svg

          # Options
          template: classic
          base: ""
          user: jeffl8n
          config_timezone: ${{ vars.USER_TIMEZONE }}
          repositories_skipped: |
            ${{ vars.REPOS_SKIPPED }}
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30

          
  header-jel3-sf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SF_METRICS_TOKEN }}

          filename: jel3-sf-header.svg

          # Options
          template: classic
          base: header
          user: jel3-sf
          config_timezone: ${{ vars.USER_TIMEZONE }}
          repositories_skipped: |
            ${{ vars.REPOS_SKIPPED }}

  activity-jel3-sf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SF_METRICS_TOKEN }}

          filename: jel3-sf-activity.svg

          # Options
          template: classic
          base: activity
          user: jel3-sf
          config_timezone: ${{ vars.USER_TIMEZONE }}
          repositories_skipped: |
            ${{ vars.REPOS_SKIPPED }}
          repositories_affiliations: owner, collaborator

  repositories-jel3-sf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SF_METRICS_TOKEN }}

          filename: jel3-sf-repositories.svg

          # Options
          template: classic
          base: repositories
          user: jel3-sf
          config_timezone: ${{ vars.USER_TIMEZONE }}
          repositories_skipped: |
            ${{ vars.REPOS_SKIPPED }}
          repositories_affiliations: owner, collaborator

  iso_calender-jel3-sf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SF_METRICS_TOKEN }}

          filename: jel3-sf-iso_calender.svg

          # Options
          template: classic
          base: ""
          user: jel3-sf
          config_timezone: ${{ vars.USER_TIMEZONE }}
          repositories_skipped: |
            ${{ vars.REPOS_SKIPPED }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  achievements-jel3-sf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SF_METRICS_TOKEN }}

          filename: jel3-sf-achievements.svg

          # Options
          template: classic
          base: achievements
          user: jel3-sf
          config_timezone: ${{ vars.USER_TIMEZONE }}
          repositories_skipped: |
            ${{ vars.REPOS_SKIPPED }}
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0

  languages-jel3-sf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SF_METRICS_TOKEN }}

          filename: jel3-sf-languages.svg

          # Options
          template: classic
          base: ""
          user: jel3-sf
          config_timezone: ${{ vars.USER_TIMEZONE }}
          repositories_skipped: |
            ${{ vars.REPOS_SKIPPED }}
          repositories_affiliations: owner, collaborator
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage

  habits-jel3-sf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SF_METRICS_TOKEN }}

          filename: jel3-sf-habits.svg

          # Options
          template: classic
          base: ""
          user: jel3-sf
          config_timezone: ${{ vars.USER_TIMEZONE }}
          repositories_skipped: |
            ${{ vars.REPOS_SKIPPED }}
          repositories_affiliations: owner, collaborator
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
